name: Prettier Format Check
'on':
  pull_request:
    branches:
      - main
      - prettier
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: '${{ github.head_ref }}'
          token: '${{ secrets.github_token }}'
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Update npm
        run: npm install -g npm
      - name: Install Dependencies
        run: npm ci
      - name: Format code
        run: npx prettier --write .
      - name: Commit changes
        run: >
          git config --local user.email "action@github.com"

          git config --local user.name "GitHub Action"

          git diff --quiet && git diff --staged --quiet || (git add . && git
          commit -m "Apply prettier changes")
      - name: Push changes
        run: git push
