name: Prettier Format Check
on:
  pull_request:
    branches:
      - main
      - prettier
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: '${{ github.head_ref }}'
          token: '${{ secrets.GH_PAT }}'
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          only_changed: True
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          branch: ${{ github.head_ref }}
